### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mitchlloyd** [mitchlloyd/ember-autosave#21]
- [x] Remove `AutosaveProxy.create({ content: model })`. I've already overridden this so that it takes additional arguments. Might make a new name `AutosaveProxy.wrap(model, config)`. This can avoid reserving `content`. Related issue: #20 
- [ ] ~Remove string function reference option for `save` function. This kind of thing is no longer conventional~.
- [x] Avoid runloop/debounce to lower maintenance cost.
- [x] Explore `new AutosaveProxy(...)` vs `AutosaveProxy.create(...)`
- [x] Travis CI updates
